### ISSUE TITLE
Dirty money

### ISSUE THREAD

**Issue by b4b4s666** [Madriax/Apartments#6]
message en francais suivra

hello i use your script on my own server and i tryed the function deposit dirty money work nice but when you try too withdraw that dirty money its does nothing and you dont even see a stephane message so its look like the command for that part is broken can you check that out please 

bonjour jutilise ton script sur mon propre serveur et jai essayer la fonction deposer de largent sale jusqua ce point tout va bien a 100 % mais lorsque jessay de retirer cette argent rien ne ce passe meme pas de message de stephane ( example argent insufisant ou autre ) pourrais tu verifier cette parti du script svp je crois quil y a une erreur a ce point merci a lavance jatten de tes nuvelle ( je vais verifier de mon coter aussi si je parvient a reparer je te le fais suivre )

**Comment by b4b4s666** [comment]
i fixed it in the file apart_server.lua in section: 
 RegisterServerEvent("apart:takedirtycash") near line 221 under this section check for : 
if (result) then
            money = result[1].money
and switch it for : 
if (result) then
            money = result[1].dirtymoney 
and problem seem to be fix :)

jai reparer dans le fichier apart_server.lua dans la section: 
 RegisterServerEvent("apart:takedirtycash") pres de la  ligne 221 en dessous de cette section regarder pour : 
if (result) then
            money = result[1].money
et changer le pour : 
if (result) then
            money = result[1].dirtymoney 

et le probleme semble etre resolu :)

**Comment by b4b4s666** [comment]
just created a pull request using your file you can check and aprove it if you want

**Comment by Madriax** [comment]
done
