### ISSUE TITLE
price

### ISSUE THREAD

**Issue by b4b4s666** [Madriax/Apartments#8]
is it possible to add the function show price somewhere in the script so when you try to buy a house if you dont have enough cash example its say not enough money and under ( ) the price appear or something else 

bonjour esce possible dajouter le prix des maison lorsque on essaye de lacheter et que lon a pas assez dargent sa dit argent inssufisant mais esce possible de rajouter le prix a la suite quelque part merci

**Comment by b4b4s666** [comment]
jai trouver et coder le tout moi meme jai creer un pull request maintenant on voit le prix de chaque appartement avant de lacheter

i fixed this check pull request !! now showing price before buying !!

**Comment by Madriax** [comment]
done
